<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tn ti khon_uname</name>
   <tag></tag>
   <elementGuidId>6fa51c76-6842-423e-8486-4e1da8b78fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0c9fa51-6693-4145-b92a-56b6a938a33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0242adbd-cf78-4be4-8039-cc2c58e9a49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>c40d3d3f-92f2-488a-ad6c-6fd8ad998efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>febe9197-d591-406e-8df6-83f840df0f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uname</value>
      <webElementGuid>00a20de1-8694-4a10-84b8-7d51bb953521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập Tên tài khoản</value>
      <webElementGuid>b4a190ce-65b0-4776-9d7d-58bb3e276710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uname&quot;)</value>
      <webElementGuid>85ccaf83-4ef5-452c-be27-b61e4b3863bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uname']</value>
      <webElementGuid>ba2e8f92-6cb1-4604-bfbb-f8a87be5df80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='widget-form-65ae1c1bdf9c9']/div/div[2]/div/div/input</value>
      <webElementGuid>8a9b983a-4fe8-4175-b4a6-f62f8d84cef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>56fb0989-094f-45ea-b8eb-ab59fe48d8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uname' and @name = 'uname' and @placeholder = 'Nhập Tên tài khoản']</value>
      <webElementGuid>d2f9edc3-f588-44d4-95bb-8bd88e4ab1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
