<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TECHCOMBANK</name>
   <tag></tag>
   <elementGuidId>a79041ed-ae1b-400d-a2fe-8a7c54f258af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-bank_code-uv-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-bank_code-uv-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb96ab36-3adf-4cbe-83a2-c3eae897d616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>d915b259-7386-49a5-a8a6-a6c1499deb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-bank_code-uv-container</value>
      <webElementGuid>116691e8-f9db-4306-afa6-e189d031ebd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TECHCOMBANK</value>
      <webElementGuid>e55ff699-c3f9-468f-8f71-c346871a3f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×TECHCOMBANK</value>
      <webElementGuid>208c10f4-24ab-4a66-b10b-7a6d600a82c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-bank_code-uv-container&quot;)</value>
      <webElementGuid>b183d031-586f-4ffd-a2de-414fc98dc117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-bank_code-uv-container']</value>
      <webElementGuid>daa91172-cb68-44e4-8248-74596f94c84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='widget-form-65ae1c1bdf9c9']/div/div/div/span/span/span/span</value>
      <webElementGuid>13e82fc3-2b01-466c-ab71-e5655476f971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d19771e1-0b88-42e8-9a4a-6c241c2652d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-bank_code-uv-container' and @title = 'TECHCOMBANK' and (text() = '×TECHCOMBANK' or . = '×TECHCOMBANK')]</value>
      <webElementGuid>d4ae0419-fc51-4557-a1b6-7981f999f3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
