<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListVA</name>
   <tag></tag>
   <elementGuidId>cff7bd4c-3e30-4bb0-af1a-f7bf729261d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/section[2]/div/div/div/div[3]/table/tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/section[2]/div/div/div/div[3]/table/tbody/tr</value>
      <webElementGuid>75728f3f-8f87-4fb9-a6d9-42c65d67a54f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
