<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English</name>
   <tag></tag>
   <elementGuidId>a73dfb1c-24a2-4867-b61b-1a206eaa5615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_auth_lang_menu']/div[2]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>281a6e49-8b3c-4e21-bb3a-2c210ef1eaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-element</name>
      <type>Main</type>
      <value>lang-name</value>
      <webElementGuid>b28fe07c-2ff0-4118-9405-4d2073d78d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>49e6726c-0a57-4b93-9748-ba6549eb3301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_auth_lang_menu&quot;)/div[@class=&quot;menu-item px-3&quot;]/a[@class=&quot;menu-link d-flex px-5&quot;]/span[2]</value>
      <webElementGuid>6c2c2e0a-383f-4cb4-8559-64d361e3c2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_auth_lang_menu']/div[2]/a/span[2]</value>
      <webElementGuid>3d2c0cc7-d1c8-4396-a7bd-c396c87b7bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span[2]</value>
      <webElementGuid>3c40b7f2-c69b-4691-a285-dae502205a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>dd411b5d-a4a8-4f1d-a7ba-4adfbb4363ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
