<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S tin thanh ton ti thiu l 10,000 VND</name>
   <tag></tag>
   <elementGuidId>b68e0c00-8722-4a45-901c-6e20dbaa6ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-form-explain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mpos-container']/div[2]/div/div/div[2]/form/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7dbce935-cac7-497c-b752-162d717dd074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-form-explain</value>
      <webElementGuid>8dae6181-bf5f-45fc-83b2-84ee18bc08ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Số tiền thanh toán tối thiểu là 10,000 VND</value>
      <webElementGuid>ba4c746c-604c-4dd7-97e6-7dbdb37b565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpos-container&quot;)/div[@class=&quot;body-mpos ant-row&quot;]/div[@class=&quot;sp-mg-15 content-mpos ant-card&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-16&quot;]/form[@class=&quot;c_form ant-form ant-form-horizontal&quot;]/div[@class=&quot;c-form-body&quot;]/div[@class=&quot;pb-0 ant-row&quot;]/div[@class=&quot;amount-left ant-col ant-col-xs-16 ant-col-lg-18&quot;]/div[@class=&quot;ant-row ant-form-item ant-form-item-with-help&quot;]/div[@class=&quot;ant-col ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control has-error&quot;]/div[@class=&quot;ant-form-explain&quot;]</value>
      <webElementGuid>e7935ea8-c249-45a2-a63d-8ffd161f1d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpos-container']/div[2]/div/div/div[2]/form/div/div/div/div/div/div/div</value>
      <webElementGuid>7ce83b4d-005b-47d1-9bac-32929d239678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div</value>
      <webElementGuid>e267a7dc-6d69-4054-b733-5f81c65440ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Số tiền thanh toán tối thiểu là 10,000 VND' or . = 'Số tiền thanh toán tối thiểu là 10,000 VND')]</value>
      <webElementGuid>224421d0-b857-4bab-9455-704cd9ebd128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
