<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_VND</name>
   <tag></tag>
   <elementGuidId>6c551265-7397-40e2-8430-80e829e2c319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-selection-selected-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mpos-container']/div[2]/div/div/div[2]/form/div/div/div[2]/div/div/div/span/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7adfeeec-37c1-4aa0-b615-e21023221199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VND</value>
      <webElementGuid>61254f52-17a4-4e21-8846-41b8421d80aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-selected-value</value>
      <webElementGuid>c53b3717-ac03-41fe-b1d8-70984d15f92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> VND </value>
      <webElementGuid>f644c47b-0b50-4079-bd57-1b309dd14fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpos-container&quot;)/div[@class=&quot;body-mpos ant-row&quot;]/div[@class=&quot;sp-mg-15 content-mpos ant-card&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-16&quot;]/form[@class=&quot;c_form ant-form ant-form-horizontal&quot;]/div[@class=&quot;c-form-body&quot;]/div[@class=&quot;pb-0 ant-row&quot;]/div[@class=&quot;currency-right ant-col ant-col-xs-8 ant-col-lg-6&quot;]/div[@class=&quot;ant-row ant-form-item&quot;]/div[@class=&quot;ant-col ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control&quot;]/span[@class=&quot;ant-form-item-children&quot;]/div[@class=&quot;form-control mt-5 ant-select ant-select-enabled ant-select-focused&quot;]/div[@class=&quot;ant-select-selection ant-select-selection--single&quot;]/div[@class=&quot;ant-select-selection__rendered&quot;]/div[@class=&quot;ant-select-selection-selected-value&quot;]</value>
      <webElementGuid>e5e760df-470b-4e2e-b2b7-43db8f955527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpos-container']/div[2]/div/div/div[2]/form/div/div/div[2]/div/div/div/span/div/div/div/div</value>
      <webElementGuid>addce536-2583-4e36-8c69-c5ae57a8ee58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div</value>
      <webElementGuid>5bb4e290-0e2d-453d-83cb-84f125b35159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'VND' and (text() = ' VND ' or . = ' VND ')]</value>
      <webElementGuid>2b06062a-e25f-4b3b-8af4-f246264e3f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
