<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1902087908</name>
   <tag></tag>
   <elementGuidId>33b85815-fac9-4a4c-b261-b2d32ff8e0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.info-merchant-span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mpos-container']/div[2]/div/div/div/div/div[3]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b62fec49-aacd-48a4-9c66-a7cc430a243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info-merchant-span</value>
      <webElementGuid>6f5f0bf5-55d1-4f9f-b405-e2fd82eb1000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1902087908</value>
      <webElementGuid>150d7a6b-7fe5-4149-9925-8cbb81e55604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpos-container&quot;)/div[@class=&quot;body-mpos ant-row&quot;]/div[@class=&quot;sp-mg-15 content-mpos ant-card&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-8&quot;]/div[@class=&quot;bg-white info&quot;]/div[@class=&quot;px-2 py-3&quot;]/div[@class=&quot;mb-1 info-merchant-item&quot;]/div[@class=&quot;info-merchant-span&quot;]</value>
      <webElementGuid>d0eda3c3-15c2-4d1f-ac66-5e208dfab21c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpos-container']/div[2]/div/div/div/div/div[3]/div[2]/div[2]</value>
      <webElementGuid>6066c68d-8c6f-4761-85ff-66320c2b9f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>db332637-1d96-4d3a-b21e-ac60671be275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1902087908' or . = '1902087908')]</value>
      <webElementGuid>14156d33-dd24-4ba5-b3fc-5b30ffe0e878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
