<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_shop sop</name>
   <tag></tag>
   <elementGuidId>8dcc2ce3-9d22-4385-8049-d1a8f6c69614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.f-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mpos-container']/div[2]/div/div/div/div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6f9309b-dca5-42e5-a1c5-2f482d4f90ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f-16</value>
      <webElementGuid>fe74f18b-2417-49fc-aa4d-4b4164274508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shop sop</value>
      <webElementGuid>4dd30b7a-9e19-404c-b91e-d6e3b2872b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mpos-container&quot;)/div[@class=&quot;body-mpos ant-row&quot;]/div[@class=&quot;sp-mg-15 content-mpos ant-card&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-8&quot;]/div[@class=&quot;bg-white info&quot;]/div[@class=&quot;px-2 py-3&quot;]/div[@class=&quot;mb-3 description&quot;]/span[@class=&quot;f-16&quot;]</value>
      <webElementGuid>7d9b0266-4d50-4ec6-9476-c5528e5a3cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mpos-container']/div[2]/div/div/div/div/div[3]/div/span</value>
      <webElementGuid>8aadbf18-878e-4cd3-bcf2-4af9e9ba65c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>3ba1c184-254e-4edb-b469-188ded3ad175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'shop sop' or . = 'shop sop')]</value>
      <webElementGuid>53bfdb68-c160-4831-bd21-528aa06144ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
