<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NINH123</name>
   <tag></tag>
   <elementGuidId>3a2a3909-cc50-4cce-91ab-83bbfb72a4c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='grid-table65adea4f9e527']/tbody/tr/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.column-account_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0d28a4c9-d995-4ce1-a7d8-e35865371231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>column-account_name</value>
      <webElementGuid>c78dc6ab-a01a-469a-8739-3fed5f45ea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        NINH123
                    </value>
      <webElementGuid>180f7492-73b3-4d2d-96b7-82c019325095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-table65adea4f9e527&quot;)/tbody[1]/tr[1]/td[@class=&quot;column-account_name&quot;]</value>
      <webElementGuid>e242a0e0-7ac9-46fb-a15b-e9cd2660e6b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='grid-table65adea4f9e527']/tbody/tr/td[6]</value>
      <webElementGuid>bda8e689-dec0-4e2a-b7ed-3f46e1be4729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>63e2aa97-e84d-47ba-9d32-8873b1c44373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                        NINH123
                    ' or . = '
                        NINH123
                    ')]</value>
      <webElementGuid>1a8edc00-b471-4340-8d52-08a4ea83edd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
