<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign out</name>
   <tag></tag>
   <elementGuidId>3083518f-9dac-4ab8-a74a-2d8690b77936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_sidebar_footer']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-flex.btn-sm.flex-center.btn-custom.btn-danger.overflow-hidden.text-nowrap.px-0.h-40px.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc3f6bdf-b746-48d3-a320-367c0fc9d8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>45bae819-47f5-4229-a118-a3ed53454067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>c85c940a-a3a4-40cf-8df9-ed607a56bb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss-</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>fb60e2ec-abe6-4393-b389-5f6d3f46cff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>200+ in-house components and 3rd-party plugins</value>
      <webElementGuid>1dda4072-4275-4f68-90dd-6536933c0225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-initialized</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4d4d6ae-4859-4194-ac37-c651f40cd551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flex btn-sm flex-center btn-custom btn-danger overflow-hidden text-nowrap px-0 h-40px w-100</value>
      <webElementGuid>6f19eefe-3229-4e43-876a-c2b8c51a962e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Sign out
         </value>
      <webElementGuid>bf60ff4f-7dd1-4933-b328-0ae1b4b2e498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_sidebar_footer&quot;)/a[@class=&quot;btn btn-flex btn-sm flex-center btn-custom btn-danger overflow-hidden text-nowrap px-0 h-40px w-100&quot;]</value>
      <webElementGuid>f4b1507e-e35d-472e-9fea-081bc136c1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_sidebar_footer']/a</value>
      <webElementGuid>2496717c-8f30-420c-957f-14490a9447b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>2d3d382a-dd8c-4d77-a0bb-d24ac9719357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
            Sign out
         ' or . = '
            Sign out
         ')]</value>
      <webElementGuid>a2c1379d-05d8-4aa5-9edf-33546cf739fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
