<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Qun l s d</name>
   <tag></tag>
   <elementGuidId>33cd3c22-422a-49c7-ad0a-1c662b358120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='deposit_withdrawal']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deposit_withdrawal > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>888d1d50-1d9c-4efd-91ee-5d6ab9e60522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3654404b-fd7f-49c4-b114-a29e737f8741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Quản lý số dư</value>
      <webElementGuid>8554b74c-7793-4fe0-acb9-9b9dab093dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deposit_withdrawal&quot;)/a[1]</value>
      <webElementGuid>a468bdbf-836b-4a8e-85d7-a352c8701e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='deposit_withdrawal']/a</value>
      <webElementGuid>417735ca-189c-4a0c-85da-613a2e50614f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quản lý số dư')]</value>
      <webElementGuid>1ece956f-a32a-42be-906f-a2ad9d3fd238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>baea6006-f3fe-4fd4-8217-74e7c5580c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a</value>
      <webElementGuid>a727eb2b-5db8-4919-81fa-0de34c1538da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '  Quản lý số dư' or . = '  Quản lý số dư')]</value>
      <webElementGuid>626a5055-1865-49b8-88b3-d5a435b6902b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
