<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_path2</name>
   <tag></tag>
   <elementGuidId>77e71efe-24bf-4929-aa5c-0dc2b8b8ba9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_sidebar_mobile_toggle']/i/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.path2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e2449d6-cb33-4dee-a4de-ed4f028c3bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path2</value>
      <webElementGuid>e7cb04f9-152e-4a2f-9c79-0738b41d5fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_sidebar_mobile_toggle&quot;)/i[@class=&quot;ki-duotone ki-abstract-14 fs-2 fs-md-1&quot;]/span[@class=&quot;path2&quot;]</value>
      <webElementGuid>75ed96db-7207-455e-acdb-3f0f62b2f990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_sidebar_mobile_toggle']/i/span[2]</value>
      <webElementGuid>c5aa769e-43d9-4b5f-b1cb-157224750840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>7c15d991-8a7b-40b7-9fcf-df061604209f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
