<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_USD balance_rounded-1</name>
   <tag></tag>
   <elementGuidId>ba632433-0163-4d26-afbe-28df7ea38d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_header_wrapper']/div[2]/div[2]/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ecda1d8-81f9-4f6b-8533-12cb1bfca712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-element</name>
      <type>Main</type>
      <value>lang-flag</value>
      <webElementGuid>c871fe92-3516-4a1d-a141-df857cb55816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/npay/assets/static/v4/landing/landing_v4/en.svg</value>
      <webElementGuid>b508fd50-2597-4110-b366-318bdfa5ea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-1</value>
      <webElementGuid>cd172f27-f29b-4a75-99e4-9ac12d654fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_header_wrapper&quot;)/div[@class=&quot;app-navbar flex-shrink-0&quot;]/div[@class=&quot;app-navbar-item ms-1 ms-md-4&quot;]/a[@class=&quot;btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-35px h-35px show menu-dropdown&quot;]/span[@class=&quot;symbol symbol-20px me-4&quot;]/img[@class=&quot;rounded-1&quot;]</value>
      <webElementGuid>7d1ac093-4c87-45ad-8dae-adcd4b1bd5ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_header_wrapper']/div[2]/div[2]/a/span/img</value>
      <webElementGuid>7e52b53b-904f-4a3d-9d08-a8776ccbd464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://storage.googleapis.com/npay/assets/static/v4/landing/landing_v4/en.svg')]</value>
      <webElementGuid>44e5b454-8ee5-4185-aeb0-2c14194236b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>515a5a5d-2b94-4ce8-994b-65ec4daad78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/npay/assets/static/v4/landing/landing_v4/en.svg']</value>
      <webElementGuid>71a2682f-0edb-4280-92f8-143fd7e79cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
