<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English</name>
   <tag></tag>
   <elementGuidId>0107422a-6d54-4db8-833e-e23f8fe6e9ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_header_wrapper']/div[2]/div[2]/div/div[2]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-link.px-3.py-2.active > span.menu-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13cb0639-ffa2-44d6-9ab8-a07f9b934c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>49cbbeef-f659-4ef9-8b6d-1510db8a0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                  English
                              </value>
      <webElementGuid>36bd5b36-a5b7-49de-b565-d0753d4d8252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_header_wrapper&quot;)/div[@class=&quot;app-navbar flex-shrink-0&quot;]/div[@class=&quot;app-navbar-item ms-1 ms-md-4&quot;]/div[@class=&quot;menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-title-gray-700 menu-icon-gray-500 menu-active-bg menu-state-color fw-semibold py-4 fs-base w-150px show&quot;]/div[@class=&quot;menu-item px-3 my-0&quot;]/a[@class=&quot;menu-link px-3 py-2 active&quot;]/span[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>2a64e1a8-f10c-4cd3-93f6-5d2ecd7c6a22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_header_wrapper']/div[2]/div[2]/div/div[2]/a/span[2]</value>
      <webElementGuid>0bfef2cb-b17e-4cb9-9944-0fe317faf260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span[2]</value>
      <webElementGuid>82f927ab-0688-4eec-8f58-cf7e204ea522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                  English
                              ' or . = '
                                  English
                              ')]</value>
      <webElementGuid>d605f361-b311-4b71-b931-c3d606ea609e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
