<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ting vit_ki-duotone ki-down fs-5 text-muted m-0</name>
   <tag></tag>
   <elementGuidId>55596a2b-c01a-4c59-9fbb-4f240c7fcc2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_page']/div/div/div/div[2]/div/button/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ki-duotone.ki-down.fs-5.text-muted.m-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f2406c73-befb-45f7-b471-3cfd3f7ef499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ki-duotone ki-down fs-5 text-muted m-0</value>
      <webElementGuid>e0dd5b9c-afc0-40a9-b768-d9fe12747855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_page&quot;)/div[1]/div[@class=&quot;d-flex flex-column flex-lg-row flex-column-fluid&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row-fluid w-lg-50 p-10 order-2 order-lg-1&quot;]/div[@class=&quot;d-flex flex-stack px-10 mx-auto&quot;]/div[@class=&quot;me-10&quot;]/button[@class=&quot;btn btn-flex btn-link btn-color-gray-700 btn-active-color-primary rotate fs-base&quot;]/span[@class=&quot;d-flex flex-center rotate-180&quot;]/i[@class=&quot;ki-duotone ki-down fs-5 text-muted m-0&quot;]</value>
      <webElementGuid>8dee2a52-d6b8-47b9-aa42-5e8cacf3b373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_page']/div/div/div/div[2]/div/button/span[2]/i</value>
      <webElementGuid>a5d37323-1325-4a4b-9b3d-c05a47aec1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>0dac6bcf-e261-43af-8f4c-233bd5a68013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
