<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NINH123</name>
   <tag></tag>
   <elementGuidId>7906460a-5ca7-499f-8c7c-707b799757c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.column-account_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/section[2]/div/div/div/div[3]/table/tbody/tr[1]/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1d5e8467-10c5-46fe-af56-9c24cdd3332e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>column-account_name</value>
      <webElementGuid>d71b8fc6-ba20-49de-8d81-3b8dfeaac5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        NINH123
                    </value>
      <webElementGuid>6165f943-7f70-4bdd-891c-f104f7c3001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-table65aa402606aeb&quot;)/tbody[1]/tr[1]/td[@class=&quot;column-account_name&quot;]</value>
      <webElementGuid>c1357abe-dd32-487a-8420-f0d0f2cc74f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/section[2]/div/div/div/div[3]/table/tbody/tr[1]/td[6]</value>
      <webElementGuid>2a7c551f-1d4e-49e6-a901-e50619d0cb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>db265bb2-3b33-4405-93cb-3c821e8534cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                        NINH123
                    ' or . = '
                        NINH123
                    ')]</value>
      <webElementGuid>a40baad6-b5ef-465e-a274-9a0cb1776180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
