<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-control card-shop__info_1_2_3</name>
   <tag></tag>
   <elementGuidId>f3b80047-f1e4-4701-9ef7-728b5c99d60a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div[2]/div/div/form/div[4]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5e0e6be-f364-46cc-bb21-a3a70478ca6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ac8cb80-c113-45d8-a202-c66a3c15ff3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ</value>
      <webElementGuid>45ae9cbc-5566-426a-abf4-4f3ec1a34fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control card-shop__info</value>
      <webElementGuid>f3251af3-42c6-4298-9693-135af8ae2612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-8&quot;]/div[@class=&quot;card mb-5&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;fv-row mb-3&quot;]/input[@class=&quot;form-control card-shop__info&quot;]</value>
      <webElementGuid>826b78b1-80b7-44be-aa56-c322a0705d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>31d665c2-c5fe-4b9c-a87b-23a7192b0a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div[2]/div/div/form/div[4]/input</value>
      <webElementGuid>7731e765-a6ac-4429-9c9f-9d15486c2c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>48681ece-0d50-4735-a514-4155fdd5f07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Địa chỉ']</value>
      <webElementGuid>f7231d6a-2df7-4ce1-a9f5-8a114ab3c715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
