<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ti khon ngun                                                             autotest</name>
   <tag></tag>
   <elementGuidId>110543a3-5dae-4d16-9389-ad2a87dbd89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;user_source_id&quot;]&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='user_source_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>753ecd77-fd92-41d7-be93-2f1aecdce4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_source_id</value>
      <webElementGuid>78306404-1301-48db-9a30-263dfa864166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cca2d761-c9a4-4b15-b0e1-bab66e38b683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tài khoản nguồn
                                                             autotest</value>
      <webElementGuid>0e41a87a-4cf7-49b7-86b1-0b4ce03de04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1b6fd525-8296-401d-8132-b8f60f2a41a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='user_source_id']</value>
      <webElementGuid>123be047-adb0-4b12-a207-ea8b0e680aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_form']/div/div/div/select</value>
      <webElementGuid>cc48e68d-0c02-435c-8cba-a4a2e1f0f2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1fb9973b-c95c-4d38-b2c7-cbd1724c6cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user_source_id' and (text() = 'Tài khoản nguồn
                                                             autotest' or . = 'Tài khoản nguồn
                                                             autotest')]</value>
      <webElementGuid>7732cf8a-58ff-4d3d-82ef-023c5d9ab763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/main/div/div[2]/div/div/div[2]/div/div/div/div/form/div/div[1]/div[1]/select</value>
      <webElementGuid>466fa17e-6fdb-481c-bacb-3956585b90b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
